origin: {latitude: 1.47, longitude: 102.11, elevation: 0.0}
default_speed_mps: 0.75
waypoints:
- {name: start_a, x: 10.8, y: -8.7, speed: 0.38}
- {name: pre_gate8, x: 12.0, y: -4.0, speed: 0.57}
- {name: gate8_approach, x: 12.0, y: -1.0, speed: 0.46}
- {name: gate8_center, x: 12.0, y: 0.0, speed: 0.41}
- {name: gate8_exit, x: 12.0, y: 1.0, speed: 0.46}
- {name: gate9_approach, x: 12.0, y: 3.8, speed: 0.46}
- {name: gate9_center, x: 12.0, y: 4.8, speed: 0.41}
- {name: gate9_exit, x: 12.0, y: 5.8, speed: 0.46}
- {name: gate10_approach, x: 12.0, y: 7.8, speed: 0.43}
- {name: gate10_center, x: 12.0, y: 8.8, speed: 0.38}
- {name: gate10_exit, x: 12.0, y: 9.8, speed: 0.32}
- {name: top_right_entry, x: 12.0, y: 10.8, speed: 0.32}
- {name: top_right_turn, x: 11.2, y: 11.6, speed: 0.32}
- {name: corner_top_right, x: 9.2, y: 12.0, speed: 0.32}
- {name: gate7_approach, x: 7.2, y: 12.0, speed: 0.35}
- {name: gate7_center, x: 6.2, y: 12.0, speed: 0.32}
- {name: gate7_exit, x: 5.2, y: 12.0, speed: 0.35}
- {name: gate6_approach, x: 3.4, y: 12.0, speed: 0.35}
- {name: gate6_center, x: 2.4, y: 12.0, speed: 0.32}
- {name: gate6_exit, x: 1.4, y: 12.0, speed: 0.35}
- {name: gate5_approach, x: -0.4, y: 12.0, speed: 0.35}
- {name: gate5_center, x: -1.4, y: 12.0, speed: 0.32}
- {name: gate5_exit, x: -2.4, y: 12.0, speed: 0.35}
- {name: gate4_approach, x: -4.2, y: 12.0, speed: 0.35}
- {name: gate4_center, x: -5.2, y: 12.0, speed: 0.32}
- {name: gate4_exit, x: -6.2, y: 12.0, speed: 0.35}
- {name: corner_top_left, x: -8.2, y: 12.0, speed: 0.32}
- {name: top_left_turn, x: -11.2, y: 11.6, speed: 0.32}
- {name: gate3_approach, x: -12.0, y: 9.8, speed: 0.32}
- {name: gate3_center, x: -12.0, y: 8.8, speed: 0.38}
- {name: gate3_exit, x: -12.0, y: 7.8, speed: 0.43}
- {name: gate2_approach, x: -12.0, y: 5.8, speed: 0.46}
- {name: gate2_center, x: -12.0, y: 4.8, speed: 0.41}
- {name: gate2_exit, x: -12.0, y: 3.8, speed: 0.46}
- {name: gate1_approach, x: -12.0, y: 1.0, speed: 0.46}
- {name: gate1_center, x: -12.0, y: 0.0, speed: 0.41}
- {name: gate1_exit, x: -12.0, y: -1.0, speed: 0.46}
- {name: post_gate1_exit, x: -11.2, y: -3.8, speed: 0.47}
- {name: surface_photo_approach, x: -8.5, y: -3.8, speed: 0.47}
- {name: surface_photo_green_box, x: -8.2, y: -5.4, speed: 0.22}
- {name: surface_photo_retreat, x: -8.2, y: -7.0, speed: 0.47}
- {name: underwater_photo_approach, x: -8.5, y: -7.5, speed: 0.47}
- {name: underwater_photo_blue_box, x: -9.0, y: -7.7, speed: 0.22}
- {name: photo_exit_south, x: -8.0, y: -9.8, speed: 0.54}
- {name: path_13, x: -12.4, y: -9.8, speed: 0.75}
- {name: path_14, x: -2.0, y: -11.2, speed: 0.75}
- {name: path_15, x: 4.0, y: -11.2, speed: 0.75}
- {name: return_south, x: 9.0, y: -12.0, speed: 0.75}
- {name: dock_align_south, x: 11.5, y: -12.0, speed: 0.4}
- {name: dock_entry, x: 11.5, y: -11.0, speed: 0.3}
- {name: dock_side_align, x: 11.5, y: -9.7, speed: 0.22}
- {name: dock_contact_blue_buoys, x: 12.5, y: -9.7, speed: 0.18, docking: true}
